### ISSUE TITLE
kubeflow-dashboard-operator fails on linting, integration tests, and upload charm in GH runner on track/1.7

### ISSUE THREAD

**Issue by i-chvets** [canonical/kubeflow-dashboard-operator#137]
# Description
Discovered during running on pull request workflows when not related image retrieval script was checked in.
Linting is failing when running `tox -c . -e lint` in the workflow.
This PR has the logs/traces for failing tests https://github.com/canonical/kubeflow-dashboard-operator/pull/136

Need to review and address failing lint test.

# Solution
This script that was added does not affect functinality of this charm, however CI started to fail on this PR (based on `track/1.7`): linting, integration tests, and publishing.
In order to solve this issue with minimal changes/updates to track/1.7 `pyyaml` was pinned to `>6.0`.

**Comment by kimwnasptd** [comment]
I don't see any further work done in this issue on getting to the root cause, and only focusing on reporting the issue, so I'll have to ask the following questions.

I don't understand why "suddenly" linting is failing. In order for linting to fail it means some package version was updated, but this is not the case. If a PR updated some package version that makes linting fail this should have been caught on that PR. So how did we end up with failed linting
1. after the last PR did not have any issue with linting?
2. on a PR that doesn't update any package version?

**Comment by i-chvets** [comment]
Addition script to tools/ directory to collect images cause CI re-run. There were multiple failuires in linting, intgeration test and charm publishing.

There should not have been any of this issues present, but they appeared. We still have no root cause.

Lininting is solved.
Jira was updated.
The following PRs were updated to get to the bottom of what is going on on tack/1.7:
https://github.com/canonical/pipelines-rocks/pull/28
@i-chvets
[fix: unpin juju](https://github.com/canonical/kubeflow-dashboard-operator/pull/139/commits/9c2e088d0991e8a067ac8e5fdc399fd8ee60f52b)
[9c2e088](https://github.com/canonical/kubeflow-dashboard-operator/pull/139/commits/9c2e088d0991e8a067ac8e5fdc399fd8ee60f52b)
@i-chvets
[fix: pin juju <3.0](https://github.com/canonical/kubeflow-dashboard-operator/pull/139/commits/8b495f4e86d87afda62437992d1742d233a022be)
[8b495f4](https://github.com/canonical/kubeflow-dashboard-operator/pull/139/commits/8b495f4e86d87afda62437992d1742d233a022be)
@i-chvets
[fix: added tmate](https://github.com/canonical/kubeflow-dashboard-operator/pull/139/commits/74341a3c32f8edaac3414c9354431d2830c458e6)
[74341a3](https://github.com/canonical/kubeflow-dashboard-operator/pull/139/commits/74341a3c32f8edaac3414c9354431d2830c458e6)
@i-chvets
[fix: updated requirements and remove tmate](https://github.com/canonical/kubeflow-dashboard-operator/pull/139/commits/28139b554e2beef1b1d3a7f7b99678f057549b51)
[28139b5](https://github.com/canonical/kubeflow-dashboard-operator/pull/139/commits/28139b554e2beef1b1d3a7f7b99678f057549b51)
@i-chvets
[fix: updated requirements](https://github.com/canonical/kubeflow-dashboard-operator/pull/139/commits/4561713e31f05c426553f0a7bebab9451994bf5c)
[4561713](https://github.com/canonical/kubeflow-dashboard-operator/pull/139/commits/4561713e31f05c426553f0a7bebab9451994bf5c)
@i-chvets
[fix: pinned pyyaml](https://github.com/canonical/kubeflow-dashboard-operator/pull/139/commits/a42b150fb04f03990d48fcaf6ed1cfb670d9573c)
[a42b150](https://github.com/canonical/kubeflow-dashboard-operator/pull/139/commits/a42b150fb04f03990d48fcaf6ed1cfb670d9573c)

**Comment by i-chvets** [comment]
Aditional PRs to tests solitions:
https://github.com/canonical/kubeflow-dashboard-operator/pull/140
https://github.com/canonical/kubeflow-dashboard-operator/pull/142

**Comment by i-chvets** [comment]
Integration test failures:
8m 13s
Run sg microk8s -c "tox -e integration -- --model kubeflow"
integration: install_deps> python -I -m pip install -r requirements-integration.txt
integration: freeze> python -m pip freeze --all
integration: anyio==3.7.[1](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/5625002184/job/15270688089#step:6:1),asttokens==2.2.1,async-generator==1.10,attrs==22.2.0,backcall==0.2.0,bcrypt==4.0.1,blinker==1.5,Brotli==1.0.9,cachetools==5.3.0,certifi==2022.12.7,cffi==1.15.1,charset-normalizer==3.1.0,cryptography==39.0.2,decorator==5.1.1,exceptiongroup==1.1.1,executing==1.2.0,google-auth==2.1[6](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/5625002184/job/15270688089#step:6:7).2,h11==0.14.0,h2==4.1.0,hpack==4.0.0,httpcore==0.1[7](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/5625002184/job/15270688089#step:6:8).3,httpx==0.24.1,hyperframe==6.0.1,idna==3.4,iniconfig==2.0.0,ipdb==0.13.13,ipython==[8](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/5625002184/job/15270688089#step:6:9).11.0,jedi==0.18.2,Jinja2==3.1.2,juju==2.[9](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/5625002184/job/15270688089#step:6:10).44.0,jujubundlelib==0.5.7,kaitaistruct==0.10,kubernetes==26.1.0,lightkube==0.14.0,lightkube-models==1.27.1.4,macaroonbakery==1.3.1,MarkupSafe==2.1.2,matplotlib-inline==0.1.6,mypy-extensions==1.0.0,oauthlib==3.2.2,outcome==1.2.0,packaging==23.0,paramiko==2.12.0,parso==0.8.3,pexpect==4.8.0,pickleshare==0.7.5,pip==23.2,pluggy==1.0.0,prompt-toolkit==3.0.38,protobuf==3.20.3,ptyprocess==0.7.0,pure-eval==0.2.2,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycparser==2.21,Pygments==2.14.0,pymacaroons==0.13.0,PyNaCl==1.5.0,pyOpenSSL==23.0.0,pyparsing==3.0.9,pyRFC3339==1.1,PySocks==1.7.1,pytest==7.2.2,pytest-asyncio==0.21.0,pytest-operator==0.26.0,python-dateutil==2.8.2,pytz==2022.7.1,PyYAML==6.0.1,requests==2.28.2,requests-oauthlib==1.3.1,rsa==4.9,selenium==4.8.2,selenium-wire==5.1.0,setuptools==68.0.0,six==1.16.0,sniffio==1.3.0,sortedcontainers==2.4.0,stack-data==0.6.2,theblues==0.5.2,tomli==2.0.1,toposort==1.10,traitlets==5.9.0,trio==0.22.0,trio-websocket==0.10.2,typing-inspect==0.8.0,typing_extensions==4.5.0,urllib3==1.26.15,wcwidth==0.2.6,websocket-client==1.5.1,websockets==7.0,wheel==0.40.0,wsproto==1.2.0,zstandard==0.20.0
integration: commands[0]> pytest -v --tb native --asyncio-mode=auto /home/runner/work/kubeflow-dashboard-operator/kubeflow-dashboard-operator/tests/integration --log-cli-level=INFO -s --model kubeflow
============================= test session starts ==============================
platform linux -- Python 3.8.[10](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/5625002184/job/15270688089#step:6:11), pytest-7.2.2, pluggy-1.0.0 -- /home/runner/work/kubeflow-dashboard-operator/kubeflow-dashboard-operator/.tox/integration/bin/python
cachedir: .tox/integration/.pytest_cache
rootdir: /home/runner/work/kubeflow-dashboard-operator/kubeflow-dashboard-operator, configfile: pyproject.toml
plugins: anyio-3.7.1, operator-0.26.0, asyncio-0.21.0
asyncio: mode=auto
collecting ... collected 5 items

tests/integration/test_charm.py::test_build_and_deploy 
-------------------------------- live log setup --------------------------------
INFO     pytest_operator.plugin:plugin.py:641 Connecting to existing model github-pr-6cccd-microk8s:kubeflow on unspecified cloud
-------------------------------- live log call ---------------------------------
INFO     pytest_operator.plugin:plugin.py:492 Using tmp_path: /home/runner/work/kubeflow-dashboard-operator/kubeflow-dashboard-operator/.tox/integration/tmp/pytest/kubeflow0
INFO     pytest_operator.plugin:plugin.py:948 Building charm kubeflow-dashboard
INFO     pytest_operator.plugin:plugin.py:955 Charm build for kubeflow-dashboard completed with errors (return code=1) in 466.25s
FAILED
tests/integration/test_charm.py::test_add_profile_relation XFAIL (ab...)
tests/integration/test_charm.py::test_status XFAIL (aborted)
tests/integration/test_charm.py::test_default_sidebar_links XFAIL (a...)
tests/integration/test_charm.py::test_configmap_contents XFAIL (aborted)
------------------------------ live log teardown -------------------------------
INFO     pytest_operator.plugin:plugin.py:756 Model status:

Model     Controller                Cloud/Region        Version  SLA          Timestamp
kubeflow  github-pr-6cccd-microk8s  microk8s/localhost  2.9.44   unsupported  16:46:15Z



INFO     pytest_operator.plugin:plugin.py:762 Juju error logs:


INFO     pytest_operator.plugin:plugin.py:830 Forgetting main...


=================================== FAILURES ===================================
____________________________ test_build_and_deploy _____________________________
Traceback (most recent call last):
  File "/home/runner/work/kubeflow-dashboard-operator/kubeflow-dashboard-operator/tests/integration/test_charm.py", line 83, in test_build_and_deploy
    my_charm = await ops_test.build_charm(".")
  File "/home/runner/work/kubeflow-dashboard-operator/kubeflow-dashboard-operator/.tox/integration/lib/python3.8/site-packages/pytest_operator/plugin.py", line 977, in build_charm
    raise RuntimeError(
RuntimeError: Failed to build charm .:
Packing the charm.
Launching environment to pack for base name='ubuntu' channel='20.04' architectures=['amd64'] (may take a while the first time but it's reusable)
Packing the charm
Packing the charm.
Building charm in '/root'
Running step PULL for part 'charm'
Running step BUILD for part 'charm'
Parts processing error: Failed to run the build script for part 'charm'.
Failed to build charm for bases index '0'.
Full execution log: '/home/runner/.local/state/charmcraft/log/charmcraft-20230723-163829.752177.log'


------------------------------ Captured log setup ------------------------------
INFO     pytest_operator.plugin:plugin.py:641 Connecting to existing model github-pr-6cccd-microk8s:kubeflow on unspecified cloud
------------------------------ Captured log call -------------------------------
INFO     pytest_operator.plugin:plugin.py:492 Using tmp_path: /home/runner/work/kubeflow-dashboard-operator/kubeflow-dashboard-operator/.tox/integration/tmp/pytest/kubeflow0
INFO     pytest_operator.plugin:plugin.py:948 Building charm kubeflow-dashboard
INFO     pytest_operator.plugin:plugin.py:955 Charm build for kubeflow-dashboard completed with errors (return code=1) in 466.25s
=============================== warnings summary ===============================
tests/integration/test_charm.py::test_build_and_deploy
tests/integration/test_charm.py::test_build_and_deploy
  /home/runner/work/kubeflow-dashboard-operator/kubeflow-dashboard-operator/.tox/integration/lib/python3.8/site-packages/websockets/protocol.py:218: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
    self._drain_lock = asyncio.Lock(loop=loop)

tests/integration/test_charm.py: 48 warnings
  /home/runner/work/kubeflow-dashboard-operator/kubeflow-dashboard-operator/.tox/integration/lib/python3.8/site-packages/websockets/protocol.py:977: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
    yield from asyncio.sleep(self.ping_interval, loop=self.loop)

tests/integration/test_charm.py: 153 warnings
  /home/runner/work/kubeflow-dashboard-operator/kubeflow-dashboard-operator/.tox/integration/lib/python3.8/site-packages/websockets/protocol.py:9[11](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/5625002184/job/15270688089#step:6:12): DeprecationWarning: 'with (yield from lock)' is deprecated use 'async with lock' instead
    with (yield from self._drain_lock):

tests/integration/test_charm.py: 106 warnings
  /home/runner/work/kubeflow-dashboard-operator/kubeflow-dashboard-operator/.tox/integration/lib/python3.8/site-packages/websockets/protocol.py:4[16](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/5625002184/job/15270688089#step:6:17): DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
    yield from asyncio.wait(

tests/integration/test_charm.py: 46 warnings
  /home/runner/work/kubeflow-dashboard-operator/kubeflow-dashboard-operator/.tox/integration/lib/python3.8/site-packages/websockets/protocol.py:988: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
    yield from asyncio.wait_for(

tests/integration/test_charm.py::test_configmap_contents
tests/integration/test_charm.py::test_configmap_contents
  /home/runner/work/kubeflow-dashboard-operator/kubeflow-dashboard-operator/.tox/integration/lib/python3.8/site-packages/websockets/protocol.py:532: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
    yield from asyncio.wait_for(

tests/integration/test_charm.py::test_configmap_contents
tests/integration/test_charm.py::test_configmap_contents
  /home/runner/work/kubeflow-dashboard-operator/kubeflow-dashboard-operator/.tox/integration/lib/python3.8/site-packages/websockets/protocol.py:554: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
    yield from asyncio.wait_for(

tests/integration/test_charm.py::test_configmap_contents
tests/integration/test_charm.py::test_configmap_contents
  /home/runner/work/kubeflow-dashboard-operator/kubeflow-dashboard-operator/.tox/integration/lib/python3.8/site-packages/websockets/protocol.py:1077: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
    yield from asyncio.wait_for(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/integration/test_charm.py::test_build_and_deploy - RuntimeError: Failed to build charm .:
============ 1 failed, 4 xfailed, 361 warnings in 471.27s (0:07:51) ============
integration: exit 1 (472.40 seconds) /home/runner/work/kubeflow-dashboard-operator/kubeflow-dashboard-operator> pytest -v --tb native --asyncio-mode=auto /home/runner/work/kubeflow-dashboard-operator/kubeflow-dashboard-operator/tests/integration --log-cli-level=INFO -s --model kubeflow pid=[19](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/5625002184/job/15270688089#step:6:20)881
  integration: FAIL code 1 (493.38=setup[[20](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/5625002184/job/15270688089#step:6:21).98]+cmd[472.[40](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/5625002184/job/15270688089#step:6:41)] seconds)
  evaluation failed :( ([49](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/5625002184/job/15270688089#step:6:50)3.49 seconds)
Error: Process completed with exit code 1.

**Comment by i-chvets** [comment]
Upload charm failures:
6m 29s
Run canonical/charming-actions/upload-charm@2.2.2
/usr/bin/sudo snap install charmcraft --classic --channel latest/stable
charmcraft 2.3.0 from Canonical** installed
/usr/bin/sudo charmcraft pack --quiet --destructive-mode
Parts processing error: Failed to run the build script for part 'charm'.
Full execution log: '/root/.local/state/charmcraft/log/charmcraft-20230723-[1](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/5625002184/job/15270688651#step:5:1)63141.309509.log'
Error: The process '/usr/bin/sudo' failed with exit code 1
Error: Error: The process '/usr/bin/sudo' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/canonical/charming-actions/2.2.2/dist/upload-charm/index.js:3763:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/canonical/charming-actions/2.2.2/dist/upload-charm/index.js:3746:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/canonical/charming-actions/2.2.2/dist/upload-charm/index.js:3640:27)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:[10](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/5625002184/job/15270688651#step:5:11)92:[16](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/5625002184/job/15270688651#step:5:17))
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
/usr/bin/sudo test -d /root/snap/charmcraft/common/cache/charmcraft/log
No charmcraft logs generated, skipping artifact upload.

**Comment by i-chvets** [comment]
PR is ready https://github.com/canonical/kubeflow-dashboard-operator/pull/145

**Comment by i-chvets** [comment]
Fixed by https://github.com/canonical/kubeflow-dashboard-operator/pull/140 (CI issue resolution). Closing.
