### ISSUE TITLE
Update `kubeflow-dashboard` manifests

### ISSUE THREAD

**Issue by misohu** [canonical/kubeflow-dashboard-operator#190]
### Why it needs to get done

Each charm has a set of manifest files that have to be upgraded to their target version. The process of upgrading manifest files usually means going to the component’s upstream repository, comparing the charm’s manifest against the one in the repository and adding the missing bits in the charm’s manifest.

### What needs to get done

https://docs.google.com/document/d/1a4obWw98U_Ndx-ZKRoojLf4Cym8tFb_2S7dq5dtRQqs/edit?pli=1#heading=h.jt5e3qx0jypg

### When is the task considered done

1. Manifests are updated 
2. Upstream image is used

**Comment by NohaIhab** [comment]
closed by #196, https://github.com/canonical/kubeflow-tensorboards-operator/pull/112, https://github.com/canonical/katib-operators/pull/189, https://github.com/canonical/kfp-operators/pull/503, https://github.com/canonical/training-operator/pull/176
