### ISSUE TITLE
Charm's resource is not up to date in `ch:1.8/edge` and `ch:latest/edge`

### ISSUE THREAD

**Issue by DnPlas** [canonical/kubeflow-dashboard-operator#194]
### Bug Description

The `latest/edge` and `1.8/edge` Charmhub tracks have `oci-image r683` attached, but this image corresponds to the `charmedkubeflow/kubeflow-central-dashboard:1.8-0719441` container image and not to `docker.io/kubeflownotebookswg/centraldashboard:v1.8.0`, which is the expected one given the changes in #191 and #192.

#### Deploying

1. Deploy the charm from one of the tracks mentioned in the description
2. Exec into the workload container and check for the `__daemon__` user (this is added by the rock, but not by the upstream image)
3. Confirm the image comes from the rock, despite the `HEAD` of `gh:track/1.8` and `gh:main` point to the upstream image

#### Checking the publish job logs

1. Observe the latest [publish job](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/9206979214/job/25463454614#step:5:470) is attaching resource `r683`
2. Observe a previous [publish job](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/9006472350/job/25323073695#step:5:466) is also attaching the same resource, which could mean it is not updating it

### Environment

CI environment.

### Relevant Log Output

```shell
N/A
```

**Comment by mvlassis** [comment]
@DnPlas and I tried to manually upload the latest revision of `oci-image` using the `docker.io/kubeflownotebookswg/centraldashboard:v1.8.0` image, but we get the following error trying to upload the charm to Charmhub:

```
Store operation failed:
- None: No compatible resource and package revisions in release request for charm 'ScuThnuIqjZRpljgOzuhZxluTu9aDspc' to channel edge
```

**Comment by mvlassis** [comment]
We uploaded a new revision of the `oci-image` (`r686`), and the `Public Charm` action works correctly. The compatibility errors seem to stem from the previous latest revision's architecture: it was `arm64` instead of `all`. No code changes are needed.
