### ISSUE TITLE
`kubeflow_dashboard_links` nested links

### ISSUE THREAD

**Issue by misohu** [canonical/kubeflow-dashboard-operator#197]
### Why it needs to get done

Upstream introduced nested elements in the dashboard sidebar for kfp components [here](https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/manifests/base/configmap.yaml#L7). With the current implementation of `kubeflow_dashboard_links` we cant accomplish the same behavior.

### What needs to get done

- Implement `items` field specified for `DashboardLink` class in the `kubeflow_dashboard_links` library.
- Use the new field in `kfp-operator` to send the link according to upstream [changes](https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/manifests/base/configmap.yaml#L7).

### When is the task considered done

- `DashboardLink` has the items field which accepts list of `DashboardLinks`
- changes are implemented in `kfp-operators`

**Comment by misohu** [comment]
We did exploration and further implementation decisions in this issue https://github.com/canonical/kubeflow-dashboard-operator/issues/198

**Comment by DnPlas** [comment]
I have tested the CKF 1.9 dashboard and I have to say the dashboard links look messy:

![image](https://github.com/canonical/kubeflow-dashboard-operator/assets/18201737/5b444070-b282-4a62-8a05-d91faccbe8c0)

As you can see, the artifacts and executions links are placed beneath TensorBoards, which may be really misleading for people not familiar with these items. I think we should be looking forward to adding this feature soon.

**Comment by DnPlas** [comment]
After a sync with @kimwnasptd, we are rejecting this item.
