### ISSUE TITLE
Dashboard cannot be created in a model not called Kubeflow

### ISSUE THREAD

**Issue by grobbie** [canonical/kubeflow-dashboard-operator#22]
If I deploy CKF to a JuJu model called something other than `kubeflow` I get an error message in `juju status` saying that the Kubeflow dashboard requires the model to be called Kubeflow. I expect to be able to deploy Kubeflow to a model with any name I please.

**Comment by DomFleischmann** [comment]
This is a known issue which has also been filed [upstream](https://github.com/kubeflow/kubeflow/issues/6136).

**Comment by DnPlas** [comment]
Kubeflow should always be deployed in the `kubeflow` namespace, that is an upstream decision that the Charmed Kubeflow team has no option or power. The charmed kubeflow dashboard will alert users when deployed in a namespace other than `kubeflow`.
