### ISSUE TITLE
MicroK8s for Kubeflow link

### ISSUE THREAD

**Issue by grobbie** [canonical/kubeflow-dashboard-operator#26]
![image](https://user-images.githubusercontent.com/3254480/154435420-2025a913-bee5-4154-ab2a-8258db5e88ea.png)

The `MicroK8s for Kubeflow` link in the Documentation component on the dashboard links to the microk8s addon, which is discontinued. Needs to be removed or replaced with something else, for instance the Elyra tutorial when it reaches our /docs pages.

**Comment by ca-scribner** [comment]
We could add the other docs that have been generated recently by yourself and Bart at the same time

**Comment by i-chvets** [comment]
Should we link this doc? https://charmed-kubeflow.io/docs/get-started-with-charmed-kubeflow
It has `microk8s` part, but it is kinda redundant, because user already reached dashboard.
