### ISSUE TITLE
Kubeflow dashboard version

### ISSUE THREAD

**Issue by andreeamun** [canonical/kubeflow-dashboard-operator#83]
**Summary**

At the bottom of the sidebarin the Kubeflow dashboard, the version is not shown. Instead, users can see ```build version dev_local```

![image](https://user-images.githubusercontent.com/77149394/214657674-79cb0f89-de7d-4778-b65b-1f23929fb2d0.png)

**Comment by DnPlas** [comment]
This is a duplicate of #17
